### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ggdhines** [CitizenScienceInAstronomyWorkshop/pyIBCC#11]
I'm getting the following error
Traceback (most recent call last):
  File "./ibcc_analysis.py", line 75, in <module>
    ibcc.runIbcc(base_directory+"Databases/supernova_ibcc.py")
  File "/home/ggdhines/github/pyIBCC/python/ibcc.py", line 421, in runIbcc
    pT = combiner.combine_classifications(dh.crowdlabels, dh.goldlabels, optimise_hyperparams)
  File "/home/ggdhines/github/pyIBCC/python/ibcc.py", line 373, in combine_classifications
    self.optimise_hyperparams()
  File "/home/ggdhines/github/pyIBCC/python/ibcc.py", line 388, in optimise_hyperparams
    negml = self.neg_marginal_likelihood(initialguess)
  File "/home/ggdhines/github/pyIBCC/python/ibcc.py", line 354, in neg_marginal_likelihood
    self.vb_inference() #run inference algorithm
  File "/home/ggdhines/github/pyIBCC/python/ibcc.py", line 237, in vb_inference
    lnjoint = self.expec_t() 
  File "/home/ggdhines/github/pyIBCC/python/ibcc.py", line 103, in expec_t
    lnjoint = self.lnjoint()
  File "/home/ggdhines/github/pyIBCC/python/ibcc.py", line 97, in lnjoint
    return self.lnjoint_sparselist()
  File "/home/ggdhines/github/pyIBCC/python/ibcc.py", line 85, in lnjoint_sparselist
    data = self.lnPi[j,self.crowdlabels[:,2],self.crowdlabels[:,0]].reshape(-1)
IndexError: index -9223372036854775808 is out of bounds for axis 1 with size 2

The input files are:
https://www.dropbox.com/s/wpzpiy3yo0m4094/supernova_ibcc.csv?dl=0
and
https://www.dropbox.com/s/7vjpudpo0vbjobk/serengeti_ibcc.py?dl=0

**Comment by ggdhines** [comment]
I can create the error with a simple input file:
a,b,c
0,0,1
1,0,1
2,0,1
3,0,1
4,1,1
5,1,1

**Comment by ggdhines** [comment]
Nevermind - there was a single "None" instead of 0 or 1 in the 600,000 classifications.
