### ISSUE TITLE
Error loading file

### ISSUE THREAD

**Issue by ggdhines** [CitizenScienceInAstronomyWorkshop/pyIBCC#8]
Traceback (most recent call last):
  File "./clusterCompare2.py", line 87, in <module>
    agglomerative.__signal_ibcc__()
  File "/home/greg/github/reduction/experimental/paper/clustering/aggregation.py", line 683, in __signal_ibcc__
    ibcc.runIbcc(base_directory+"/Databases/"+self.project+"_ibcc.py")
  File "/home/greg/github/pyIBCC/python/ibcc.py", line 419, in runIbcc
    combiner, dh = load_combiner(configFile, ibcc_class)
  File "/home/greg/github/pyIBCC/python/ibcc.py", line 411, in load_combiner
    dh.loadData(config_file)
  File "/home/greg/github/pyIBCC/python/ibccdata.py", line 212, in loadData
    self.output_file = outputFile % testid
TypeError: not all arguments converted during string formatting

Here is the config file:
import numpy as np
scores = np.array([0,1])
nScores = len(scores)
nClasses = 2
inputFile = "/home/greg/Databases/penguin_ibcc.csv"
outputFile = "/home/greg/Databases/penguin_signal.out"
confMatFile = "/home/greg/Databases/penguin_ibcc.mat"
nu0 = np.array([77,22])
alpha0 = np.array([[12, 1], [1, 3]])

**Comment by edwinrobots** [comment]
I think this is fixed now -- if the filename doesn't include a "%i", we don't put the testid into the filenames.
